/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Oraculo, OraculoInterface } from "../Oraculo";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "getETHUSDPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50600080546001600160a01b031916737a250d5630b4cf539739df2c5dacb4c659f2488d179055610342806100466000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063bf4b199014610030575b600080fd5b61003861004e565b6040516100459190610297565b60405180910390f35b6040805160028082526060820183526000928392919060208301908036833701905050905073c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2816000815181106100a957634e487b7160e01b600052603260045260246000fd5b60200260200101906001600160a01b031690816001600160a01b03168152505073a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48816001815181106100ff57634e487b7160e01b600052603260045260246000fd5b6001600160a01b0392831660209182029290920101526000805460405163d06ca61f60e01b8152670de0b6b3a764000093919091169063d06ca61f9061014b90859087906004016102a0565b60006040518083038186803b15801561016357600080fd5b505afa158015610177573d6000803e3d6000fd5b505050506040513d6000823e601f3d908101601f1916820160405261019f91908101906101d8565b90506000816001815181106101c457634e487b7160e01b600052603260045260246000fd5b602002602001015190508094505050505090565b600060208083850312156101ea578182fd5b825167ffffffffffffffff80821115610201578384fd5b818501915085601f830112610214578384fd5b815181811115610226576102266102f6565b838102604051601f19603f8301168101818110858211171561024a5761024a6102f6565b604052828152858101935084860182860187018a1015610268578788fd5b8795505b8386101561028a57805185526001959095019493860193860161026c565b5098975050505050505050565b90815260200190565b60006040820184835260206040818501528185518084526060860191508287019350845b818110156102e95784516001600160a01b0316835293830193918301916001016102c4565b5090979650505050505050565b634e487b7160e01b600052604160045260246000fdfea26469706673582212208e124a83b3499fc9848cfa67fdea3ad2479d5e45beda334669e25a678db5866864736f6c63430008010033";

export class Oraculo__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Oraculo> {
    return super.deploy(overrides || {}) as Promise<Oraculo>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Oraculo {
    return super.attach(address) as Oraculo;
  }
  connect(signer: Signer): Oraculo__factory {
    return super.connect(signer) as Oraculo__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): OraculoInterface {
    return new utils.Interface(_abi) as OraculoInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Oraculo {
    return new Contract(address, _abi, signerOrProvider) as Oraculo;
  }
}
